const setup = require('./setup/setup.service')
const logger = require('./logger/logger.service')
const users = require('./users/users.service')
const authentication = require('./authentication/authentication.service')
const client = require('./client/client.service')
const device = require('./device/device.service')
const interfaces = require('./interfaces/interfaces.service')
const applications = require('./applications/applications.service')
const updates = require('./updates/updates.service')
const files = require('./files/files.service')
const download = require('./download/download.service')

module.exports = (app) => {
  app.configure(setup)
  app.configure(logger)
  app.configure(users)
  app.configure(authentication)
  app.configure(device)
  app.configure(interfaces)
  app.configure(applications)
  app.configure(updates)
  app.configure(files)
  app.configure(download)
  app.configure(client)
}
